Update to my environment

diff --git a/bin/xcolorpick b/bin/xcolorpick
--- a/bin/xcolorpick
+++ b/bin/xcolorpick
@@ -4,10 +4,11 @@
 ### System variables
 ###
 MY_NAME="$( basename "${0}" )"
-MY_LOG_DIR="${HOME}/.log"
+MY_LOG_DIR="${HOME}/cache/log"
 MY_LOG_FILE="${MY_LOG_DIR}/${MY_NAME}.err"
 MY_DATE="$( date '+%Y-%m-%d' )"
 MY_TIME="$( date '+%H:%M:%S' )"
+FORMAT="HEX"
 
 if [ ! -d "${MY_LOG_DIR}" ]; then
 	mkdir -p "${MY_LOG_DIR}"
@@ -39,17 +40,25 @@ error() {
 ##
 ################################################################################
 
-if ! command -v grabc >/dev/null 2>&1; then
-	error "Binary 'grabc' not available"
+if ! command -v xclip >/dev/null 2>&1; then
+	error "Binary 'xclip' not available"
 	exit 1
 fi
 
-if ! command -v zenity >/dev/null 2>&1; then
-	error "Binary 'zenity' not available."
+if ! command -v xcolor >/dev/null 2>&1; then
+	error "Binary 'xcolor' not available."
 	exit 1
 fi
 
 
-color="$( grabc )"
+color=$(xcolor -P 100 -f "$FORMAT"!)
 
-zenity --color-selection --color="${color}"
+if [[ "$color" ]]; then
+    # Copy color code to clipboard
+    echo "$color" | tr -d "\n" | xclip -selection clipboard
+    # Notify about it
+    dunstify -u low --replace=9991 -i "colorgrab" "$color, copied to clipboard."
+else
+    echo "Failed to pick color."
+    exit 1
+fi
diff --git a/bin/xf86-audio b/bin/xf86-audio
--- a/bin/xf86-audio
+++ b/bin/xf86-audio
@@ -1,6 +1,5 @@
 #!/bin/sh -eu
 
-
 ################################################################################
 #
 # VARIABLES
@@ -9,11 +8,10 @@
 
 ACTION=
 INTERVAL="3"
+NOTIFICATION_TIMEOUT=1000
 DEVICE=""
 MIXER="Master"
 COMMAND=
-
-
 
 ################################################################################
 #
@@ -22,42 +20,49 @@ COMMAND=
 ################################################################################
 
 print_usage_head() {
-	printf "Usage: %s [OPTIONS] -c COMMAND\n" "${0}"
-	printf "       %s -a\n"  "${0}"
-	printf "       %s -h\n"  "${0}"
+    printf "Usage: %s [OPTIONS] -c COMMAND\n" "${0}"
+    printf "       %s -a\n" "${0}"
+    printf "       %s -h\n" "${0}"
 }
+
 print_usage() {
-	print_usage_head
+    print_usage_head
 
-	printf "\nThis script is a wrapper for amixer that will change the volume\n"
-	printf "and send those changes to a notification daemine.\n\n"
+    printf "\nThis script is a wrapper for pamixer that will change the volume\n"
+    printf "and send those changes to a notification daemon.\n\n"
 
-	printf "COMMAND:\n"
-	printf "  -c up           Increase volume.\n"
-	printf "  -c down         Decrease volume.\n"
-	printf "  -c mute         Mute volume.\n"
-	printf "  -c toggle       Toggle mute/unmute.\n\n"
+    printf "COMMAND:\n"
+    printf "  -c up           Increase volume.\n"
+    printf "  -c down         Decrease volume.\n"
+    printf "  -c mute         Mute volume.\n"
+    printf "  -c toggle       Toggle mute/unmute.\n\n"
 
-	printf "OPTIONS:\n"
-	printf "   -i <interval>  Change the interval for volume up/down.\n"
-	printf "                  The default is 3 (percent).\n\n"
+    printf "OPTIONS:\n"
+    printf "   -i <interval>  Change the interval for volume up/down.\n"
+    printf "                  The default is 3 (percent).\n\n"
 
-	printf "   -D <device>    Specify a device, such as 'pulse'.\n"
-	printf "                  If omitted using 'default'.\n\n"
+    printf "   -D <device>    Specify a device, such as 'pulse'.\n"
+    printf "                  If omitted using 'default'.\n\n"
 
-	printf "   -M <mixer>     If omitted using 'Master'.\n"
-	printf "                  Use -a to show all mixers.\n\n"
+    printf "   -M <mixer>     If omitted using 'Master'.\n"
+    printf "                  Use -a to show all mixers.\n\n"
 
-	printf "HELP:\n"
-	printf "   -a             Show all mixers.\n"
-	printf "   -h             Show help.\n"
+    printf "HELP:\n"
+    printf "   -a             Show all mixers.\n"
+    printf "   -h             Show help.\n"
 }
 
 get_all_mixers() {
-	 amixer | grep -E '^\w.*$' | grep -Eo "'.*'" | sed "s/'//g"
+    pamixer --list-sinks | awk '{print $1}'
 }
 
-
+check_sink_existence() {
+    local sink="$1"
+    if ! pamixer --list-sinks | grep -q "^$sink "; then
+        printf "Error: The sink '%s' doesn't exist.\n" "$sink"
+        exit 1
+    fi
+}
 
 ################################################################################
 #
@@ -68,61 +73,63 @@ get_all_mixers() {
 ############################################################
 # Parse arguments
 ############################################################
-while [ "${#}" -gt 0  ]; do
-	case "${1}" in
-		-c)
-			shift
-			if [ "${1}" != "up" ] && [ "${1}" != "down" ] && [ "${1}" != "mute" ] && [ "${1}" != "toggle" ]; then
-				printf "Error, -c must either be 'up', 'down', 'mute' or 'toggle'.\n"
-				print_usage_head
-				exit 1
-			fi
-			ACTION="${1}"
-			;;
-		-i)
-			shift
-			if ! printf "%d" "${1}" >/dev/null 2>&1; then
-				printf "Error, the value for -i must be an integer.\n"
-				print_usage_head
-				exit 1
-			fi
-			INTERVAL="${1}"
-			;;
-		-D)
-			shift
-			DEVICE="${1}"
-			;;
-		-M)
-			shift
-			MIXER="${1}"
-			;;
-		-a)
-			get_all_mixers
-			exit
-			;;
-		-h)
-			print_usage
-			exit
-			;;
-		*)
-			printf "Unknown argument: %s\n" "${1}"
-			print_usage_head
-			exit 1
-			;;
-	esac
-	shift
+while [ "${#}" -gt 0 ]; do
+    case "${1}" in
+        -c)
+            shift
+            if [ "${1}" != "up" ] && [ "${1}" != "down" ] && [ "${1}" != "mute" ] && [ "${1}" != "toggle" ]; then
+                printf "Error, -c must either be 'up', 'down', 'mute' or 'toggle'.\n"
+                print_usage_head
+                exit 1
+            fi
+            ACTION="${1}"
+            ;;
+        -i)
+            shift
+            if ! printf "%d" "${1}" >/dev/null 2>&1; then
+                printf "Error, the value for -i must be an integer.\n"
+                print_usage_head
+                exit 1
+            fi
+            INTERVAL="${1}"
+            ;;
+        -D)
+            shift
+            DEVICE="${1}"
+            ;;
+        -M)
+            shift
+            MIXER="${1}"
+            ;;
+        -a)
+            get_all_mixers
+            exit
+            ;;
+        -h)
+            print_usage
+            exit
+            ;;
+        *)
+            printf "Unknown argument: %s\n" "${1}"
+            print_usage_head
+            exit 1
+            ;;
+    esac
+    shift
 done
 
 ############################################################
 # Check required arguments
 ############################################################
 if [ "${ACTION}" = "" ]; then
-	printf "Error, -c is mandatory.\n"
-	print_usage_head
-	exit 1
+    printf "Error, -c is mandatory.\n"
+    print_usage_head
+    exit 1
 fi
 
-
+if [ "${DEVICE}" != "" ]; then
+    check_sink_existence "$DEVICE"
+fi
 
 ################################################################################
 #
@@ -136,80 +143,52 @@ fi
 
 # Use specific device?
 if [ "${DEVICE}" != "" ]; then
-	DEVICE="-D ${DEVICE}"
+    DEVICE="--sink ${DEVICE}"
 fi
 
 # Build command
 if [ "${ACTION}" = "up" ]; then
-	COMMAND="amixer ${DEVICE} sset ${MIXER} '${INTERVAL}%+' unmute"
+    COMMAND="pamixer ${DEVICE} --increase ${INTERVAL}"
 elif [ "${ACTION}" = "down" ]; then
-	COMMAND="amixer ${DEVICE} sset ${MIXER} '${INTERVAL}%-' unmute"
+    COMMAND="pamixer ${DEVICE} --decrease ${INTERVAL}"
 elif [ "${ACTION}" = "mute" ]; then
-	COMMAND="amixer ${DEVICE} sset ${MIXER} mute"
+    COMMAND="pamixer ${DEVICE} --toggle-mute"
 else
-	COMMAND="amixer ${DEVICE} sset ${MIXER} toggle"
+    COMMAND="pamixer ${DEVICE} --toggle-mute"
 fi
-
 
 ############################################################
 # Run command
 ############################################################
 
-OUTPUT="$( eval "${COMMAND}" )"
-
+OUTPUT="$(eval "${COMMAND}")"
 
 ############################################################
 # Parse output
 ############################################################
 
-PERCENT="$( echo "${OUTPUT}" | grep -m 1 "%]" | cut -d "[" -f2 | cut -d "%" -f1 )"
+PERCENT="$(pamixer ${DEVICE} --get-volume)"
 MUTED=0
-if ! amixer get "${MIXER}" | grep -q '\[on\]'; then
-	MUTED=1
+if pamixer ${DEVICE} --get-mute | grep -q "true"; then
+    MUTED=1
 fi
-
 
 ############################################################
 # Get notification icon/text
 ############################################################
-
 if [ "${MUTED}" = "1" ]; then
-	ICON_STRING="notification-audio-volume-muted"
-	TEXT_STRING="vol: muted"
-	PERCENT=0
+    ICON_STRING="volume-level-muted"
+    TEXT_STRING="Volume: MUTED"
+    PERCENT=0
 else
-	if [ "${PERCENT}" -lt "33" ]; then
-		ICON_STRING="notification-audio-volume-low"
-	else
-		if [ "${PERCENT}" -lt "67" ]; then
-			ICON_STRING="notification-audio-volume-medium"
-		else
-			ICON_STRING="notification-audio-volume-high"
-		fi
-	fi
-
-
-	i=$(( PERCENT / 10 ))
-	j=$(( 10 - i ))
-	TEXT_STRING="vol: "
-	while [ $i -gt 0 ]; do
-		TEXT_STRING="${TEXT_STRING}–"
-		i=$(( i - 1 ))
-	done
-	TEXT_STRING="${TEXT_STRING}|"
-	while [ $j -gt 0 ]; do
-		TEXT_STRING="${TEXT_STRING}–"
-		j=$(( j - 1 ))
-	done
-
-	TEXT_STRING="${TEXT_STRING} ${PERCENT}%"
-
+    ICON_STRING="audio-volume-high"  # Use papirus theme for muted icon
+    TEXT_STRING="Volume: ${PERCENT}%"
 fi
-
 
 ############################################################
 # Send notification
 ############################################################
-
-notify-send "${TEXT_STRING}" -i ${ICON_STRING} -h int:value:${PERCENT} -h string:synchronous:volume
+if [ "${ACTION}" = "up" ] || [ "${ACTION}" = "down" ]; then
+    notify-send "${TEXT_STRING}" -i ${ICON_STRING} -t ${NOTIFICATION_TIMEOUT} -u low -h int:value:${PERCENT} -h string:synchronous:volume
+fi
 exit
